import numpy as np
from scipy.special import erfc
from helpers import linear_to_dB, dB_to_linear

q = 1.602e-19      # electron charge (C)
k = 1.38e-23       # Boltzmann constant (J/K)

class OpticalNoiseV2:

    def __init__(self, P_R:float, wavelength:float, B_e:float, T:float=300, R:float=50, eta:float=0.9, i_D:float=1e-9, detector_type:str="PIN", detector_material:str="ingaas", M:float=1):
        """
        :param P_R: Received optical power at the photodetector [W]
        :type P_R: float
        :param wavelength: Wavelength of the optical signal [m]
        :type wavelength: float
        :param B_e: Electrical bandwidth of the receiver [Hz]
        :type B_e: float
        :param T: Receiver temperature [K], default is 300 K
        :type T: float
        :param R: Load resistance [Ohm], default is 50 Ohm
        :type R: float
        :param eta: Photodiode quantum efficiency (0.30 to 0.95 typical), default is 0.9
        :type eta: float
        :param i_D: Dark current of the photodiode [A], default is 1 nA
        :type i_D: float
        :param detector_type: Type of photodetector ("PIN" or "APD"), default is "PIN"
        :type detector_type: str
        :param detector_material: Material of the photodetector ("Si", "InGaAs", "Ge"), default is "InGaAs"
        :type detector_material: str
        :param M: Avalanche gain for APD (ignored for PIN), default is 1
        :type M: float
        """
        self.P_R = P_R  # Received optical power [W]
        self.wavelength = wavelength  # Wavelength [m]
        self.B_e = B_e  # Electrical receiver bandwidth [Hz]
        self.T = T  # Receiver temperature [K]
        self.R = R  # Load resistance [Ohm]
        self.eta = eta  # Photodiode quantum efficiency [-] (30% to 95% typical)
        self.i_D = i_D  # Dark current [A]

        self.detector_type = detector_type.upper()  # "PIN" or "APD"
        self.detector_material = detector_material.lower()  # "si", "ingaas" or "ge"

        match self.detector_type:
            case "APD":
                match self.detector_material:
                    case "si":
                        x = 0.3
                    case "ingaas":
                        x = 0.7
                    case "ge":
                        x = 1.0
                    case _:
                        raise ValueError("Invalid detector material. Must be 'Si', 'InGaAs', or 'Ge'.")
                self.M = M  # Avalanche gain for APD
                self.F = M ** x  # Excess noise factor for APD
            case "PIN":
                self.M = 1  # No gain for PIN
                self.F = 1  # No excess noise for PIN
            case _:
                raise ValueError("Invalid detector type. Must be 'PIN' or 'APD'.")

        # constants
        self.q = 1.602176634e-19  # electron charge (C)
        self.h = 6.62607015e-34  # Planck's constant (J*s)
        self.c = 299792458  # speed of light (m/s)
        self.kB = 1.380649e-23  # Boltzmann constant (J/K)

        # Calculate everything
        self.sigmaShot = self.shotNoise()
        self.sigmaDark = self.darkNoise()
        self.sigmaThermal = self.thermalNoise()
        self.sigmaTotal = self.totalNoise()
        self.SNR = self.SNR()

    def responsivity(self):
        """
        Calculate photodetector responsivity [A/W] based on quantum efficiency and wavelength.
        """
        return self.eta * self.q * self.wavelength / (self.h * self.c) * self.M

    def photocurrent(self):
        """
        Calculate photocurrent generated by the received optical power [A].
        """
        return self.responsivity() * self.P_R

    def shotNoise(self):
        """
        Calculate shot noise. [A^2]
        """
        return 2 * self.q * self.photocurrent() * self.B_e * (self.M ** 2) * self.F

    def darkNoise(self):
        """
        Calculate dark current noise. [A^2]
        """
        return 2 * self.q * self.i_D * self.B_e * (self.M ** 2) * self.F

    def thermalNoise(self):
        """
        Calculate thermal noise. [A^2]
        """
        return 4 * self.kB * self.T / self.R * self.B_e

    def totalNoise(self):
        """
        Calculate total noise. [A^2]
        """
        return self.sigmaShot + self.sigmaDark + self.sigmaThermal

    def SNR(self, ):
        """
        Calculate signal-to-noise ratio (SNR) at the photodetector output (dimensionless).
        """
        return self.photocurrent() ** 2 / self.totalNoise()

    def summary(self, in_dB: bool = False, Print: bool = True, save: bool = False, filename: str = "opticalNoiseSummary.txt"):
        if in_dB:
            summary_str = f"""
            === Optical Noise Summary ===
            --- Inputs ---
            P_R (Received Optical Power): {self.P_R:.3e} W
            Wavelength: {self.wavelength:.3e} m
            B_e (Electrical Bandwidth): {self.B_e:.3e} Hz
            T (Temperature): {self.T:.1f} K
            R (Load Resistance): {self.R:.3f} Ohm
            eta (Quantum Efficiency): {self.eta:.3f}
            i_D (Dark Current): {self.i_D:.3e} A
            Detector Type: {self.detector_type}
            Detector Material: {self.detector_material}
            Avalanche Gain (M): {self.M:.3f}

            --- Noise Components ---
            Shot noise: {linear_to_dB(self.sigmaShot):.3f} dB
            Dark current noise: {linear_to_dB(self.sigmaDark):.3f} dB
            Thermal noise: {linear_to_dB(self.sigmaThermal):.3f} dB

            --- Total Noise ---
            Total noise: {linear_to_dB(self.sigmaTotal):.3f} dB

            --- Performance Metrics ---
            SNR: {linear_to_dB(self.SNR):.3f} dB
            """
        else:
            summary_str = f"""
            === Optical Noise Summary ===
            --- Inputs ---
            P_R (Received Optical Power): {self.P_R:.3e} W
            Wavelength: {self.wavelength:.3e} m
            B_e (Electrical Bandwidth): {self.B_e:.3e} Hz
            T (Temperature): {self.T:.1f} K
            R (Load Resistance): {self.R:.3f} Ohm
            eta (Quantum Efficiency): {self.eta:.3f}
            i_D (Dark Current): {self.i_D:.3e} A
            Detector Type: {self.detector_type}
            Detector Material: {self.detector_material}
            Avalanche Gain (M): {self.M:.3f}

            --- Noise Components ---
            Shot noise: {self.sigmaShot:.3e} A^2
            Dark current noise: {self.sigmaDark:.3e} A^2
            Thermal noise: {self.sigmaThermal:.3e} A^2

            --- Total Noise ---
            Total noise: {self.sigmaTotal:.3e} A^2

            --- Performance Metrics ---
            SNR: {self.SNR:.3e}
            """
        if Print:
            print(summary_str)
        if save:
            with open(filename, 'w') as f:
                f.write(summary_str)


### RUN HERE
#example = opticalNoise(I1=1e-3, I0=1e-6, B=10e9, RIN=dB_to_linear(-145), eta_PD=0.9, eta_RX=1000, eta_LD=0.5, eta_FO=1, I_TX_RMS=1e-6, i_dark=10e-9, R_load=50, T=300)
#example.summary(True)

exampleV2 = OpticalNoiseV2(P_R=1e-3, wavelength=1550e-9, B_e=1e9, T=300, R=50, eta=0.9, i_D=1e-9, detector_type="APD", detector_material="InGaAs", M=10)
exampleV2.summary(True)